INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (1, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (2, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (3, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (4, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (5, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (6, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (7, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (8, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (9, "", "", NULL, NULL, NULL);
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES (10, "", "", NULL, NULL, NULL);

INSERT INTO users (id, name, age) VALUES (NULL, "", NULL);
INSERT INTO users (id, name, age) VALUES (2, "", NULL);
INSERT INTO users (id, name, age) VALUES (3, "", NULL);
INSERT INTO users (id, name, age) VALUES (4, "", NULL);
INSERT INTO users (id, name, age) VALUES (5, "", NULL);
INSERT INTO users (id, name, age) VALUES (6, "", NULL);
INSERT INTO users (id, name, age) VALUES (7, "", NULL);
INSERT INTO users (id, name, age) VALUES (8, "", NULL);
INSERT INTO users (id, name, age) VALUES (9, "", NULL);
INSERT INTO users (id, name, age) VALUES (10, "", NULL);
INSERT INTO users (id, name, age) VALUES (11, "", NULL);
INSERT INTO users (id, name, age) VALUES (12, "", NULL);
INSERT INTO users (id, name, age) VALUES (13, "", NULL);
INSERT INTO users (id, name, age) VALUES (14, "", NULL);
INSERT INTO users (id, name, age) VALUES (15, "", NULL);
INSERT INTO users (id, name, age) VALUES (16, "", NULL);
INSERT INTO users (id, name, age) VALUES (17, "", NULL);
INSERT INTO users (id, name, age) VALUES (18, "", NULL);
INSERT INTO users (id, name, age) VALUES (19, "", NULL);
INSERT INTO users (id, name, age) VALUES (20, "", NULL);

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, NULL, NULL, NULL);
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, NULL, NULL, NULL);
